import type { HistoriaQuiz } from '../../learning';
export type ChallengeQuestion = HistoriaQuiz & { tricky: boolean };
// Answers are shuffled by the sampler. Existing scene quizzes remain unchanged.
const q = (
  question: string,
  correct: string,
  other: string,
  third: string,
  explanation: string,
  tricky = false,
): ChallengeQuestion => ({
  question,
  options: [correct, other, third],
  correctIndex: 0,
  explanation,
  tricky,
});
export const challengeQuestions: Record<
  1 | 2 | 3,
  Record<number, ChallengeQuestion>
> = {
  1: {
    1: q(
      'Du reist am Nil von Unterägypten nach Oberägypten. In welche Richtung geht es?',
      'Nach Süden, gegen die Fließrichtung',
      'Nach Norden, mit der Fließrichtung',
      'Nach Süden, mit der Fließrichtung',
      'Unterägypten liegt am nördlichen Delta. Oberägypten liegt südlich und flussaufwärts – „oben“ meint nicht den oberen Kartenrand.',
      true,
    ),
    2: q(
      'Was lässt sich aus dem Bau der Cheops-Pyramide über den Staat schließen?',
      'Er konnte Fachwissen, Versorgung und viele Arbeitskräfte organisieren.',
      'Er brauchte militärische Stärke, aber kaum Verwaltung.',
      'Er überließ Planung und Versorgung allein einzelnen Familien.',
      'Das Großprojekt erforderte koordinierte Planung und Versorgung. Es zeigt auch die organisatorische Macht des Königtums.',
    ),
    3: q(
      'Hammurabis Recht war öffentlich sichtbar. Bedeutete das Gleichheit vor dem Recht?',
      'Nein: Der gesellschaftliche Rang beeinflusste die Anwendung.',
      'Ja: Die Veröffentlichung machte den Rang bedeutungslos.',
      'Ja: Gleiche Rechtssätze bedeuteten für alle dieselben Strafen.',
      'Ein öffentlich festgehaltenes Recht ist noch kein gleiches Recht für alle. Der soziale Rang spielte eine wichtige Rolle.',
      true,
    ),
    4: q(
      'Ramses stellte Kadesch als großen Erfolg dar. Was bedeutet das für unsere Bewertung?',
      'Seine Siegesdarstellung muss vom unklaren Schlachtausgang unterschieden werden.',
      'Seine Darstellung belegt eine eindeutige Niederlage der Hethiter.',
      'Der spätere Friedensvertrag beweist, dass Ramses damals klar verloren hatte.',
      'Herrscher stellen Ereignisse zu ihren Gunsten dar. Bei Kadesch gab es keinen eindeutigen Sieger; der spätere Vertrag beweist keinen damaligen Sieg.',
    ),
    5: q(
      'Warum waren Provinzen und Berichte für Dareios ebenso wichtig wie Straßen?',
      'Sie verbanden örtliche Verwaltung mit Entscheidungen im Zentrum.',
      'Sie machten die Provinzen unabhängig vom Großkönig.',
      'Sie ersetzten Verwaltung durch persönliche Besuche des Königs.',
      'Straßen ermöglichten Verbindungen; Provinzen und berichtende Beamte machten das riesige Reich regierbar.',
    ),
    6: q(
      'Warum konnte die Größe der persischen Flotte bei Salamis zum Nachteil werden?',
      'Die Enge begrenzte ihren Bewegungsspielraum.',
      'Die Enge erlaubte besonders viele Schiffe nebeneinander.',
      'Die Enge nahm nur der griechischen Flotte die Beweglichkeit.',
      'Die Meerenge nahm einer großen Flotte Raum zum Manövrieren. Die Griechen nutzten die Bedingungen des Schlachtorts.',
    ),
    7: q(
      'Eine freie Frau lebt im Athen des Perikles. Darf sie in der Volksversammlung abstimmen?',
      'Nein: Das Stimmrecht war freien männlichen Bürgern vorbehalten.',
      'Ja: Freiheit allein war die Voraussetzung.',
      'Ja: Wer dauerhaft in Athen lebte, durfte abstimmen.',
      'Athens Demokratie bedeutete keine politische Gleichberechtigung aller Einwohner. Frauen, Versklavte und Zugewanderte waren ausgeschlossen.',
      true,
    ),
    8: q(
      'Warum traf Lysanders Hafenblockade Athen besonders schwer?',
      'Sie griff die lebenswichtigen Seeverbindungen der Seemacht an.',
      'Sie nahm Sparta seine Überlegenheit an Land.',
      'Sie machte Athens Niederlage auf Sizilien rückgängig.',
      'Athens Stärke und Versorgung hingen an seinen Seeverbindungen. Die Blockade setzte genau dort an; 404 v. Chr. kapitulierte Athen.',
    ),
    9: q(
      'Welche Schwäche von Alexanders Reich wurde nach seinem Tod sichtbar?',
      'Seine Eroberungen waren nicht durch eine dauerhaft gesicherte Nachfolge verbunden.',
      'Die eroberten Gebiete hatten bereits vor seinem Tod Rom gehört.',
      'Seine Feldherren waren sich über eine gemeinsame Regierung einig.',
      'Nach Alexanders Tod teilten seine Feldherren das Reich auf. Militärischer Erfolg sichert noch keine dauerhafte politische Einheit.',
    ),
    10: q(
      'Was verbindet Qin Shihuangdis einheitliche Maße, Münzen und Schriftzeichen?',
      'Sie erleichterten gemeinsame Verwaltung und Kontrolle.',
      'Sie stärkten die Unabhängigkeit der früheren Teilreiche.',
      'Sie ersetzten Zwangsarbeit durch freiwillige Zusammenarbeit.',
      'Gemeinsame Standards erleichterten Verwaltung. Sie bedeuteten aber keine mildere Herrschaft: Zwangsarbeit und harte Strafen blieben bestehen.',
    ),
    11: q(
      'Warum bedeuteten Hannibals Siege in Italien noch keinen gewonnenen Krieg?',
      'Rom blieb handlungsfähig und griff Karthagos Machtbasis an.',
      'Hannibal hatte mit dem Alpenübergang schon Rom erobert.',
      'Scipios Sieg bei Zama fand vor Hannibals Alpenübergang statt.',
      'Schlachtensiege und der Sieg im gesamten Krieg sind nicht dasselbe. Rom verlagerte den Angriff; Scipio besiegte Hannibal 202 v. Chr. bei Zama.',
    ),
    12: q(
      'Caesars Gegner wollten die Republik retten. Was folgte auf seine Ermordung?',
      'Weitere Bürgerkriege statt einer dauerhaft geretteten Republik',
      'Die sofortige Rückkehr zu einer stabilen Republik',
      'Die unmittelbare Krönung Caesars zum Kaiser',
      'Die Beseitigung Caesars löste die Machtkonflikte nicht. Auf seinen Tod folgten neue Bürgerkriege.',
    ),
    13: q(
      'Wie hängt Actium mit Ägyptens späterer Stellung zusammen?',
      'Octavians Sieg ebnete den Weg zur römischen Provinz Ägypten.',
      'Antonius’ Sieg sicherte Ägyptens Unabhängigkeit.',
      'Kleopatras Sieg machte Rom zur ägyptischen Provinz.',
      'Nach Octavians Sieg starben Antonius und Kleopatra im folgenden Jahr. Ägypten wurde römische Provinz.',
    ),
    14: q(
      'Unter Augustus bestand der Senat weiter. War die entscheidende Macht deshalb wieder verteilt?',
      'Nein: Die republikanischen Formen blieben, die Macht lag bei Augustus.',
      'Ja: Der Senat beweist, dass Augustus keine Sonderstellung hatte.',
      'Ja: Augustus überließ Heer und Provinzen vollständig dem Senat.',
      'Institutionen können fortbestehen, obwohl sich tatsächliche Machtverhältnisse ändern. Augustus bündelte die entscheidende Macht.',
      true,
    ),
    15: q(
      'Was lässt sich aus der Zusicherung von 313 sicher ableiten?',
      'Christen erhielten freie Religionsausübung.',
      'Alle Bewohner des Reichs wurden Christen.',
      'Alle anderen Religionen wurden sofort verboten.',
      'Freie Religionsausübung ist weder eine allgemeine Bekehrung noch automatisch ein Verbot anderer Religionen.',
      true,
    ),
    16: q(
      'Was endete 476 – und was nicht?',
      'Das weströmische Kaisertum endete; das Reich im Osten bestand weiter.',
      'Beide römischen Reichsteile endeten gleichzeitig.',
      'Das Oströmische Reich endete; Westrom bestand weiter.',
      '476 ist ein Einschnitt für Westrom. Das Reich mit Konstantinopel bestand noch fast tausend Jahre weiter.',
      true,
    ),
  },
  2: {
    1: q(
      'Die islamische Zeitrechnung beginnt 622. Welches Ereignis steht dahinter?',
      'Mohammeds Auswanderung von Mekka nach Medina',
      'Mohammeds Geburt in Mekka',
      'Die Verlegung des Machtzentrums nach Damaskus',
      'Der Ausgangspunkt ist die Hidschra, nicht Mohammeds Geburt und nicht das spätere Machtzentrum der Umayyaden.',
      true,
    ),
    2: q(
      'Welche Zuordnung beschreibt Aachen und Rom unter Karl dem Großen richtig?',
      'Aachen: politisches Zentrum; Rom: Kaiserkrönung 800',
      'Aachen: Kaiserkrönung 800; Rom: regelmäßige Winterpfalz',
      'Aachen: Zentrum des Papstes; Rom: Karls regelmäßige Winterpfalz',
      'Aachen wurde Karls politisches Zentrum und regelmäßig genutzte Winterpfalz. Die Kaiserkrönung durch den Papst fand in Rom statt.',
    ),
    3: q(
      'Was spricht gegen die Vorstellung, Wikinger seien ausschließlich plündernde Krieger gewesen?',
      'Ihre Routen dienten auch Handel, Erkundung und Ansiedlung.',
      'Ihre Schiffe blieben auf Skandinaviens Küsten beschränkt.',
      'Ihre Reisen dienten ausschließlich der Eroberung Englands.',
      'Überfälle sind nur ein Teil der Geschichte. Ihre Routen verbanden weite Räume und ermöglichten Handel und Siedlungen.',
    ),
    4: q(
      'Was kam bei Otto I. zuerst?',
      'Der Sieg auf dem Lechfeld, dann die Kaiserkrönung',
      'Die Kaiserkrönung, dann der Sieg auf dem Lechfeld',
      'Sieg und Krönung fanden im selben Jahr statt.',
      'Der Sieg war 955, die Kaiserkrönung folgte 962. Der militärische Erfolg stärkte Ottos Stellung bereits vor der Krönung.',
    ),
    5: q(
      'Welcher Ablauf passt zu den Kreuzzügen?',
      'Aufruf in Clermont → Eroberung Jerusalems → Rückeroberung durch Saladin',
      'Eroberung Jerusalems → Aufruf in Clermont → Rückeroberung durch Saladin',
      'Aufruf in Clermont → Rückeroberung durch Saladin → erste Eroberung Jerusalems',
      'Urban II. rief 1095 zum Kreuzzug auf, Kreuzfahrer eroberten Jerusalem 1099, Saladin gewann die Stadt 1187 zurück.',
    ),
    6: q(
      'Warum war Beweglichkeit für das mongolische Heer mehr als schnelles Reiten?',
      'Sie wirkte zusammen mit Organisation und abgestimmter Kriegführung.',
      'Sie machte jede Abstimmung zwischen Truppen überflüssig.',
      'Sie ersetzte die Übermittlung von Nachrichten.',
      'Der Vorteil beruhte auf dem Zusammenspiel von Mobilität, Organisation und Taktik, nicht allein auf Geschwindigkeit.',
    ),
    7: q(
      'Warum konnte die Pest die Verhandlungsposition überlebender Arbeitskräfte verändern?',
      'Der Bevölkerungsverlust machte Arbeitskräfte knapper.',
      'Der Bevölkerungsverlust ließ das Arbeitskräfteangebot steigen.',
      'Die Pest beseitigte sofort sämtliche sozialen Abhängigkeiten.',
      'Wenn viele Menschen sterben, fehlen Arbeitskräfte. Das konnte Löhne und Abhängigkeiten verändern, bedeutete aber keine allgemeine sofortige Freiheit.',
    ),
    8: q(
      'Jeanne hilft 1429 bei Orléans. Endet damit der „Hundertjährige Krieg“ nach genau hundert Jahren?',
      'Nein: Der Name fasst einen längeren Konflikt mit Unterbrechungen zusammen.',
      'Ja: Die Schlacht beendet einen genau hundertjährigen Dauerkrieg.',
      'Nein: Der Krieg beginnt erst mit dem Erfolg bei Orléans.',
      'Der Name vereinfacht. Orléans war ein Wendepunkt, nicht das Ende eines exakt hundert Jahre dauernden ununterbrochenen Kriegs.',
      true,
    ),
    9: q(
      'Warum war Konstantinopel mehr als eine symbolisch wichtige Hauptstadt?',
      'Es lag an wichtigen Verbindungen zwischen Europa und Asien.',
      'Es kontrollierte den gesamten Atlantikhandel.',
      'Seine Lage war für Handel und Schifffahrt unbedeutend.',
      'Die Lage am Bosporus verband politische Bedeutung mit wichtigen Verkehrs- und Handelswegen.',
    ),
    10: q(
      'Kolumbus erreicht 1492 Inseln in der Karibik. Was trifft seine damalige Sicht?',
      'Er glaubte, Asien erreicht zu haben.',
      'Er wusste bereits, einen für Europäer unbekannten Kontinent erreicht zu haben.',
      'Er plante von Anfang an die spätere Eroberung des Inkareichs.',
      'Sein damaliges Weltbild und unser heutiges Wissen unterscheiden sich. Kolumbus suchte den westlichen Weg nach Asien.',
      true,
    ),
    11: q(
      'Was erklärt, warum Luthers Kritik weit über seinen unmittelbaren Ort hinauswirkte?',
      'Gedruckte Texte konnten seine Ideen schnell verbreiten.',
      'Die Kritik blieb auf mündliche Gespräche mit Fürsten beschränkt.',
      'Der Buchdruck verhinderte unterschiedliche Deutungen seiner Texte.',
      'Der Buchdruck vergrößerte die Reichweite. Er machte daraus aber weder einen einheitlichen Glauben noch einen konfliktfreien Prozess.',
    ),
    12: q(
      'Welche Unterscheidung hilft beim Verständnis des Dreißigjährigen Krieges?',
      'Der Fenstersturz war ein Auslöser; religiöse und politische Gegensätze reichten tiefer.',
      'Der Fenstersturz erklärt allein sämtliche Ursachen.',
      'Der Westfälische Frieden war der Auslöser, nicht das Ende.',
      'Ein Startsignal ist nicht die ganze Ursache. Der Krieg verknüpfte Religion und Machtinteressen; 1648 beendete ihn der Westfälische Frieden.',
    ),
    13: q(
      'Warum war Versailles auch ein politisches Instrument?',
      'Das Hofleben band Adelige an den König und erleichterte Kontrolle.',
      'Der Hof überließ dem Adel die unabhängige Verwaltung ganz Frankreichs.',
      'Der Palast beendete durch seine Pracht die Kosten der Kriege.',
      'Nähe, Rang und Abhängigkeit am Hof stärkten königliche Macht. Hofhaltung und Kriege belasteten zugleich die Finanzen.',
    ),
    14: q(
      'Was verbindet wissenschaftliches Fragen und politische Aufklärung am ehesten?',
      'Überlieferte Erklärungen und Autorität werden mit Vernunft hinterfragt.',
      'Naturgesetze begründen automatisch die absolute Herrschaft.',
      'Politische Rechte werden allein aus militärischen Erfolgen abgeleitet.',
      'Die Aufklärung betont vernünftige Prüfung statt bloßer Berufung auf Tradition. Naturwissenschaft und politische Theorie sind dabei nicht dasselbe.',
    ),
    15: q(
      'War der amerikanische Unabhängigkeitssieg allein das Werk der Kolonisten?',
      'Nein: Französische Unterstützung war entscheidend.',
      'Ja: Frankreich blieb während des gesamten Krieges neutral.',
      'Nein: Frankreich kämpfte entscheidend auf britischer Seite.',
      'Washingtons Armee kämpfte nicht isoliert. Französische Hilfe, auch militärisch, trug entscheidend zum Sieg bei.',
      true,
    ),
    16: q(
      'Welche Reihenfolge stimmt?',
      'Abschaffung der Monarchie 1792 → Napoleons Aufstieg → Waterloo 1815',
      'Napoleons Aufstieg → Waterloo 1815 → Abschaffung der Monarchie 1792',
      'Waterloo 1815 → Abschaffung der Monarchie 1792 → Napoleons Aufstieg',
      'Die Revolution schaffte 1792 die Monarchie ab. Napoleon stieg später auf; seine Rückkehr an die Macht endete 1815 bei Waterloo.',
    ),
  },
  3: {
    1: q(
      'Warum veränderte die Industrialisierung nicht nur die Herstellung von Waren?',
      'Fabriken und Eisenbahnen veränderten auch Arbeit, Wohnorte und Verbindungen.',
      'Maschinen veränderten die Produktion, ließen Lebensweisen aber gleich.',
      'Eisenbahnen machten den Austausch zwischen Regionen seltener.',
      'Produktion, Fabrikarbeit, wachsende Städte und Verkehrsnetze beeinflussten einander. Industrialisierung war ein gesellschaftlicher Wandel.',
    ),
    2: q(
      'Viele Revolutionen von 1848 scheiterten zunächst. Waren ihre Forderungen damit bedeutungslos?',
      'Nein: Rechte, Verfassungen und nationale Einheit blieben wichtige Forderungen.',
      'Ja: Mit der Niederlage verschwanden diese Forderungen.',
      'Nein: Schon 1848 wurden überall dauerhafte Demokratien errichtet.',
      'Unmittelbares Scheitern schließt langfristige Wirkung nicht aus. Umgekehrt entstanden 1848 nicht überall dauerhaft demokratische Ordnungen.',
      true,
    ),
    3: q(
      'Welche Aussage beschreibt das Ergebnis des amerikanischen Bürgerkriegs?',
      'Der Sieg der Nordstaaten bewahrte die Union und führte zur Abschaffung der Sklaverei.',
      'Der Sieg bewahrte die Union, ließ die Sklaverei aber dauerhaft unverändert.',
      'Der Sieg schaffte die Sklaverei ab und bestätigte die Abspaltung der Südstaaten.',
      'Der Sieg verhinderte die dauerhafte Teilung und führte zur Abschaffung der Sklaverei. Vollständige gesellschaftliche Gleichberechtigung war damit nicht erreicht.',
    ),
    4: q(
      'Warum war Italien bei seiner Staatsgründung 1861 noch nicht vollständig geeint?',
      'Venetien und Rom kamen erst später hinzu.',
      'Sizilien gehörte bis 1914 zu Frankreich.',
      'Turin wurde erst 1871 italienisch.',
      'Das Königreich entstand 1861. Venetien folgte 1866, Rom 1870.',
    ),
    5: q(
      '1871 wird der deutsche Kaiser in Versailles ausgerufen. Welche Verwechslung solltest du vermeiden?',
      'Der Ort lag in Frankreich, obwohl es um das Deutsche Reich ging.',
      'Versailles war die Hauptstadt des neuen Deutschen Reichs.',
      'Mit der Proklamation wurde ganz Frankreich Teil des Deutschen Reichs.',
      'Ort und Staatsgebiet sind hier nicht dasselbe. Die Proklamation fand während des Kriegs gegen Frankreich im Schloss von Versailles statt.',
      true,
    ),
    6: q(
      'Warum zeigt die Berliner Konferenz koloniale Machtungleichheit?',
      'Über Afrika wurde ohne gleichberechtigte Beteiligung afrikanischer Gesellschaften verhandelt.',
      'Afrikanische Gesellschaften bestimmten dort gemeinsam Europas Grenzen.',
      'Alle betroffenen afrikanischen Gesellschaften konnten Beschlüsse gleichberechtigt ablehnen.',
      'Regeln kolonialer Herrschaft wurden ohne gleichberechtigte Vertretung der betroffenen Menschen verhandelt.',
    ),
    7: q(
      'Warum genügt „wegen eines Attentats“ als Erklärung für den Ersten Weltkrieg nicht?',
      'Das Attentat traf auf Bündnisse, Machtkonflikte und eskalierende Entscheidungen.',
      'Das Attentat hatte keinerlei Zusammenhang mit dem Kriegsausbruch.',
      'Die Bündnisse verhinderten jede Ausweitung des Konflikts.',
      'Sarajevo war der Auslöser. Bestehende Spannungen und Entscheidungen während der Krise erklären die Ausweitung zum großen Krieg.',
    ),
    8: q(
      'Was unterscheidet Stalins Herrschaft von politischem Wettbewerb?',
      'Terror, Verfolgung und Kontrolle schalteten Gegner aus.',
      'Oppositionelle konnten die Regierung in freien Wahlen ablösen.',
      'Unabhängige Gerichte begrenzten seine Macht zuverlässig.',
      'Stalins Diktatur stützte sich auf Kontrolle und Terror. Politische Gegnerschaft war nicht als freier Wettbewerb geschützt.',
    ),
    9: q(
      'Warum geriet die Weimarer Republik ab 1929 besonders unter Druck?',
      'Massenarbeitslosigkeit und soziale Not stärkten radikale Parteien.',
      'Die Weltwirtschaftskrise machte demokratische Mehrheiten stabiler.',
      'Die Inflation von 1923 begann erst nach dem Ende der Republik.',
      'Die Weltwirtschaftskrise traf Deutschland hart. Arbeitslosigkeit und politische Blockaden schwächten das Vertrauen in die Demokratie.',
      true,
    ),
    10: q(
      'Wie gelangte Hitler 1933 unmittelbar ins Amt des Reichskanzlers?',
      'Hindenburg ernannte ihn zum Reichskanzler.',
      'Die Bevölkerung wählte ihn direkt zum Reichskanzler.',
      'Eine absolute NSDAP-Mehrheit brachte ihn automatisch ins Amt.',
      'Hindenburg ernannte Hitler. Eine direkte Wahl zum Kanzler gab es nicht; konservative Eliten ermöglichten die Machtübergabe.',
      true,
    ),
    11: q(
      'Warum war das Ermächtigungsgesetz ein entscheidender Schritt zur Diktatur?',
      'Es ermöglichte der Regierung Gesetze ohne das Parlament.',
      'Es machte die Regierung von freien Volksabstimmungen abhängig.',
      'Es stärkte die unabhängige Kontrolle durch den Reichstag.',
      'Das Gesetz entmachtete das Parlament entscheidend. Die Nationalsozialisten beseitigten demokratische Kontrolle und verfolgten Gegner.',
    ),
    12: q(
      'Warum ist 1941 für die Ausweitung des Zweiten Weltkriegs besonders wichtig?',
      'Der Angriff auf die Sowjetunion und der Kriegseintritt der USA weiteten ihn aus.',
      'Deutschland griff erstmals Polen an und begann den Krieg in Europa.',
      'Deutschland kapitulierte und die Kämpfe in Europa endeten.',
      '1939 begann der Krieg in Europa mit dem Angriff auf Polen. 1941 weiteten der Angriff auf die Sowjetunion und der Kriegseintritt der USA ihn entscheidend aus.',
    ),
    13: q(
      'Welche Aussage beschreibt die Tatorte des Holocaust zutreffend?',
      'Die Morde geschahen unter anderem in Vernichtungslagern und bei Massenerschießungen.',
      'Die Morde geschahen ausschließlich in einem einzigen Lager.',
      'Die Morde fanden ausschließlich innerhalb der deutschen Vorkriegsgrenzen statt.',
      'Der Holocaust war die systematische Ermordung der europäischen Juden. Tatorte waren unter anderem Vernichtungslager und Orte von Massenerschießungen.',
    ),
    14: q(
      'Warum war die Berliner Luftbrücke politisch bedeutsam?',
      'Sie hielt West-Berlin trotz der Blockade versorgt.',
      'Sie beendete sofort die Teilung Deutschlands.',
      'Sie verlegte West-Berlin in die westlichen Besatzungszonen.',
      'Die Luftbrücke überwand die sowjetische Blockade, vertiefte aber zugleich die Teilung.',
    ),
    15: q(
      'Warum endete die Kubakrise nicht einfach mit einem einseitigen sowjetischen Rückzug?',
      'Beide Seiten machten Zusagen und entfernten Raketen.',
      'Die USA besetzten Kuba und Moskau.',
      'Kuba trat der NATO bei.',
      'Die Sowjetunion zog Raketen aus Kuba ab; die USA versprachen keinen Angriff und entfernten später Raketen aus der Türkei.',
      true,
    ),
    16: q(
      'Warum ist Indiens Unabhängigkeit 1947 keine Erfolgsgeschichte ohne Brüche?',
      'Sie war mit Teilung, Flucht und Gewalt verbunden.',
      'Sie ließ die britische Kolonialherrschaft unverändert.',
      'Sie vereinte unmittelbar alle ehemaligen Kolonien Asiens.',
      'Unabhängigkeit und die Teilung in Indien und Pakistan gehörten zusammen. Millionen Menschen erlebten Flucht und Gewalt.',
    ),
    17: q(
      'Was bedeutet „Stellvertreterkrieg“ bei Korea und Vietnam?',
      'Örtliche Konflikte wurden mit Unterstützung rivalisierender Großmächte ausgetragen.',
      'Die beteiligten Gesellschaften hatten keinerlei eigene Interessen.',
      'Die Supermächte kämpften ausschließlich auf ihrem eigenen Gebiet.',
      'Der Begriff beschreibt den Einfluss der Großmächte, darf aber eigene Interessen und Erfahrungen der Menschen vor Ort nicht verdecken.',
    ),
    18: q(
      'Was war die EWG bei ihrer Gründung 1957?',
      'Eine Wirtschaftsgemeinschaft von sechs Staaten',
      'Bereits ein europäischer Bundesstaat',
      'Ein Militärbündnis des Ostblocks',
      'Die EWG baute wirtschaftliche Schranken zwischen sechs Mitgliedstaaten ab. Die spätere EU entwickelte sich daraus.',
    ),
    19: q(
      'Welche zeitliche Unterscheidung stimmt?',
      'Mauerfall 1989 und Wiedervereinigung 1990 sind verschiedene Ereignisse.',
      'Am Tag des Mauerfalls war die staatliche Wiedervereinigung abgeschlossen.',
      'Die Wiedervereinigung ging dem Mauerfall um ein Jahr voraus.',
      'Die Mauer öffnete sich 1989. Die staatliche Wiedervereinigung folgte 1990 – ein zusammenhängender Prozess, aber nicht ein einziges Ereignis.',
      true,
    ),
    20: q(
      'Was kennzeichnet Russlands Angriff vom 24. Februar 2022?',
      'Er weitete den seit 2014 bestehenden Krieg gegen die Ukraine massiv aus.',
      'Er begann den Krieg ohne einen vorausgehenden Krieg seit 2014.',
      'Er beendete den seit 2014 bestehenden Krieg gegen die Ukraine.',
      'Der Krieg begann nicht erst 2022. Der großangelegte Angriff weitete den seit 2014 bestehenden Krieg massiv aus.',
    ),
  },
};
